services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: procurenext
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:z

  backend:
    build:
      context: ./backend_fast_api
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend_fast_api/.env
    environment:
      PORT: 8000
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      ML_SERVICE_URL: http://ml:8001
      ML_SERVICE_TIMEOUT: 120
    volumes:
      - ./backend_fast_api:/app:z
      - ./backend_fast_api/uploads:/app/uploads:z
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - redis
      - db
      - ml

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6380:6379"

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml-service
    ports:
      - "8001:8001"
    env_file:
      - ./ml/.env
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface:z
    dns:
      - 1.1.1.1
      - 8.8.8.8

  celery_worker:
    build:
      context: ./backend_fast_api
      dockerfile: Dockerfile
    container_name: celery-worker
    env_file:
      - ./backend_fast_api/.env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      ML_SERVICE_URL: http://ml:8001
      ML_SERVICE_TIMEOUT: 120
    volumes:
      - ./backend_fast_api:/app:z
      - ./backend_fast_api/uploads:/app/uploads:z
    command: ["celery", "-A", "app.tasks.celery_app.celery_app", "worker", "--beat", "--loglevel=info"]
    depends_on:
      - redis
      - db
      - ml

  frontend:
    build: ./frontend # Builds image from Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3000:3000" # Maps container port 3000 to localhost:3000
    volumes:
      # Syncs local code with container for hot reload
      - ./frontend/app:/app/app:z
      - ./frontend/components:/app/components:z
      - ./frontend/public:/app/public:z
      - ./frontend/lib:/app/lib:z
      - ./frontend/proxy.ts:/app/proxy.ts:z
      - ./frontend/tsconfig.json:/app/tsconfig.json:z
      - ./frontend/next.config.ts:/app/next.config.ts:z
    environment:
      - WATCHPACK_POLLING=true # Makes hot reload work reliably
      - BACKEND_API_URL=http://backend:8000
    stdin_open: true # Keeps the container running
    tty: true
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
