import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'ProcureNext',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div className="flex items-center justify-center min-h-screen bg-white">
      <h1 className="text-5xl font-bold text-black">Hello World</h1>
    </div>
  );
}
