import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'ProcureNext',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', backgroundColor: 'white' }}>
      <h1>Hello World</h1>
    </div>
  );
}
