import enum

class AuditActionType(str, enum.Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    REGISTER = "REGISTER"
    SUBMIT_BID = "SUBMIT_BID"
    WITHDRAW_BID = "WITHDRAW_BID"
    ACCEPT_BID = "ACCEPT_BID"
    REJECT_BID = "REJECT_BID"
    AWARD_TENDER = "AWARD_TENDER"
    PUBLISH_TENDER = "PUBLISH_TENDER"
    CANCEL_TENDER = "CANCEL_TENDER"
    VERIFY_DOCUMENT = "VERIFY_DOCUMENT"
    PAYMENT = "PAYMENT"
    REFUND = "REFUND"
    ENLIST_VENDOR = "ENLIST_VENDOR"
    ACCESS_CHANGE = "ACCESS_CHANGE"
    SECURITY_ALERT = "SECURITY_ALERT"
    ARCHIVE_SEAL = "ARCHIVE_SEAL"

class AuditOutboxStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
